//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace razorop.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblemp
    {
        public int emp_id { get; set; }
        public string emp_name { get; set; }
        public string emp_add { get; set; }
        public string emp_mob { get; set; }
        public Nullable<System.DateTime> emp_dob { get; set; }
        public string emp_hob { get; set; }
        public string emp_gender { get; set; }
        public string emp_profile { get; set; }
        public string emp_status { get; set; }
        public int country_id { get; set; }
    
        public virtual tblcountry tblcountry { get; set; }
    }
}
